// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  CHART_BUCKET: R2Bucket;
  MASTER_KEY?: string;
  NEXT_PUBLIC_BASE_URL?: string;
}

type ChartRequestData = any;

type ChartGenerationResult = {
  id?: string;
  url?: string;
  password?: string;
  svg?: string;
};
